# Generated by Django 4.0.3 on 2022-05-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanIntrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrest_rate', models.PositiveIntegerField(blank=True, max_length=3, null=True)),
            ],
        ),
    ]
