# Generated by Django 4.0.3 on 2022-05-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_loanintrest_financel_year_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='financel_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financel_year', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='status',
            new_name='approve',
        ),
        migrations.RemoveField(
            model_name='loanintrest',
            name='financel_year',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_amount',
            field=models.PositiveIntegerField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='status_accountant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='status_president',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='status_secretary',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanintrest',
            name='reasons',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
