# Generated by Django 4.0.3 on 2022-05-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_financel_year_rename_status_loan_approve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanintrest',
            name='intrest_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
