# Generated by Django 4.0.3 on 2022-05-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_loan_loan_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanintrest',
            name='loan_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
