# Generated by Django 4.0.3 on 2022-05-29 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_loan_limit_rename_reasons_loanintrest_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Loan_installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=10, null=True)),
                ('installment_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('loan_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('intrest_on_loan', models.PositiveIntegerField(blank=True, null=True)),
                ('late_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='account.loan')),
            ],
        ),
    ]
