# Generated by Django 4.0.3 on 2022-05-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_bachat_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachat',
            name='year',
            field=models.CharField(blank=True, choices=[('1', '2021'), ('2', '2022'), ('3', '2023'), ('4', '2024'), ('5', '2025'), ('6', '2026'), ('7', '2027'), ('8', '2028'), ('9', '2029'), ('10', '2030'), ('11', '2031'), ('12', '2032'), ('13', '2033'), ('14', '2034'), ('15', '2035'), ('16', '2036'), ('17', '2037'), ('18', '2038'), ('19', '2039'), ('20', '2040')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan_installment',
            name='year',
            field=models.CharField(blank=True, choices=[('1', '2021'), ('2', '2022'), ('3', '2023'), ('4', '2024'), ('5', '2025'), ('6', '2026'), ('7', '2027'), ('8', '2028'), ('9', '2029'), ('10', '2030'), ('11', '2031'), ('12', '2032'), ('13', '2033'), ('14', '2034'), ('15', '2035'), ('16', '2036'), ('17', '2037'), ('18', '2038'), ('19', '2039'), ('20', '2040')], max_length=10, null=True),
        ),
    ]
