# Generated by Django 4.0.3 on 2022-06-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_bachat_status_accountant_alter_loan_approve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachat',
            name='status_accountant',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approve',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied'), ('Active', 'Active'), ('Closed', 'Closed')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status_accountant',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status_president',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status_secretary',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan_installment',
            name='status_accountant',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], max_length=10, null=True),
        ),
    ]
