# Generated by Django 4.0.3 on 2022-06-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_bachat_status_accountant_alter_loan_approve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status_accountant',
            field=models.CharField(blank=True, default='Pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status_president',
            field=models.CharField(blank=True, default='Pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status_secretary',
            field=models.CharField(blank=True, default='Pending', max_length=10, null=True),
        ),
    ]
